### ISSUE TITLE
No Global Menu in KDE Plasma

### ISSUE THREAD

**Issue by alxlg** [flathub/com.github.marktext.marktext#5]
See:

- https://github.com/flatpak/flatpak/issues/2012
- https://github.com/flathub/com.wire.WireDesktop/issues/3
- https://github.com/flathub/org.octave.Octave/issues/6

**Comment by fxha** [comment]
Thanks @alxlg for taking the time to report this issue. It seem we have to require permission on KDE when using the GNOME framework and a native window. I have to spin up a VM to verify this issues and fix. Which distro you use?

```
"--talk-name=com.canonical.AppMenu.Registrar",
```

**Comment by alxlg** [comment]
@fxha thank you for this cool app and the Flatpak build. I use KDE Neon.
The situation seems the same of Wire's issue I linked and the solution seems to be in this comment: https://github.com/flathub/com.wire.WireDesktop/issues/3#issuecomment-442554286

If I manually add that argument in the command line global manu indeed works
